apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-api
  labels:
    app: demo-api
spec:
  selector:
    matchLabels:
      app: demo-api
  replicas: 2
  template:
    metadata:
      labels:
        app: demo-api
    spec:
      containers:
        - name: demo-api
          image: us.gcr.io/composed-sensor-271900/demo-api
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              port: 8080
              path: /actuator/health
            initialDelaySeconds: 5
          livenessProbe:
            httpGet:
              port: 8080
              path: /actuator/health
            initialDelaySeconds: 5
          ports:
            - containerPort: 8080
          env:
            - name: message
              valueFrom:
                configMapKeyRef:
                  name: message-config
                  key: message
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: message-config
data:
  message: Hello World from GKE!
---
apiVersion: v1
kind: Service
metadata:
  name: demo-api
spec:
  selector:
    app: demo-api
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: LoadBalancer